server:
  port: 8090
  context-path: /
spring:
  level:
    #日志级别，目录: 级别
    com.company: debug
  resources:
    static-locations: classpath:dist/
    #指定静态资源路径，默认为classpath:[/META-INF/resources/,/resources/, /static/, /public/]以及context:/
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
