server:
  port: 8090
  context-path: /

spring:
  resources:
    static-locations: classpath:web/
    #指定静态资源路径，默认为classpath:[/META-INF/resources/,/resources/, /static/, /public/]以及context:/
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    view:
      prefix: /web/
      suffix: .jsp

logging:
  level:
    #日志级别，目录: 级别
    site.duqian.spring: debug
  file: log/jacoco_web.log